In [12]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import numpy as np

##### Wczytanie danych

In [98]:
df = pd.read_csv('data.csv', index_col=0).fillna(0)
df

paella   pascha wielkanocna  spaghetti bolognese  lazania  \
users                                                                       
Ula                 4.0                 5.0                  0.0      0.0   
Monika              0.0                 0.0                  0.0      0.0   
Maciek              2.0                 0.0                  5.0      5.0   
Kasper              1.0                 0.0                  1.0      0.0   
Filip               0.0                 0.0                  5.0      5.0   
Ola                 0.0                 3.0                  0.0      2.0   
Patrycja            0.0                 0.0                  0.0      4.0   
Juliusz             0.0                 0.0                  0.0      5.0   
Matusz              0.0                 0.0                  4.0      5.0   
Konrad              0.0                 0.0                  0.0      0.0   
Rafał               0.0                 0.0                  2.0      0.0   
Andrzej             0.0                 0.0                  0.0      5.0   
Mateusz Daniel      0.0                 0.0                  0.0      0.0   

                pierogi  czebureki  babka ziemniaczana  kaszanka  kutia  \
users                                                                     
Ula                 0.0        0.0                 0.0       0.0    0.0   
Monika              5.0        0.0                 5.0       3.0    0.0   
Maciek              0.0        4.0                 1.0       1.0    0.0   
Kasper              2.0        0.0                 1.0       0.0    5.0   
Filip               4.0        0.0                 4.0       3.0    0.0   
Ola                 5.0        0.0                 4.0       1.0    2.0   
Patrycja            4.0        0.0                 0.0       1.0    0.0   
Juliusz             5.0        0.0                 5.0       0.0    0.0   
Matusz              5.0        0.0                 5.0       4.0    0.0   
Konrad              5.0        0.0                 5.0       0.0    0.0   
Rafał               0.0        0.0                 2.0       0.0    0.0   
Andrzej             5.0        0.0                 3.0       0.0    5.0   
Mateusz Daniel      0.0        0.0                 0.0       0.0    0.0   

                Pizza Neapolitanska  ...  Barszcz czerwony  Schabowy  \
users                                ...                               
Ula                             0.0  ...               0.0       0.0   
Monika                          4.0  ...               5.0       0.0   
Maciek                          5.0  ...               4.0       0.0   
Kasper                          1.0  ...               0.0       5.0   
Filip                           1.0  ...               3.0       5.0   
Ola                             0.0  ...               5.0       3.0   
Patrycja                        5.0  ...               0.0       4.0   
Juliusz                         5.0  ...               3.0       5.0   
Matusz                          0.0  ...               3.0       5.0   
Konrad                          5.0  ...               5.0       0.0   
Rafał                           4.0  ...               0.0       5.0   
Andrzej                         0.0  ...               0.0       5.0   
Mateusz Daniel                  0.0  ...               1.0       5.0   

                gnocchi z chorizo i szpinakiem  Grzanka z serem  \
users                                                             
Ula                                        0.0              0.0   
Monika                                     0.0              0.0   
Maciek                                     0.0              0.0   
Kasper                                     0.0              0.0   
Filip                                      0.0              0.0   
Ola                                        0.0              0.0   
Patrycja                                   0.0              3.0   
Juliusz                                    0.0    

##### Normalizacja danych

In [99]:
scaler = StandardScaler()
scalar_fit = scaler.fit_transform(df)

##### Stworzenie modelu k-średnich, dla k = 4

In [100]:
kmeans = KMeans(n_clusters=4)
kmeans.fit(scalar_fit)
df['Group'] = kmeans.predict(scalar_fit)
df

c:\Users\Monika\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


paella   pascha wielkanocna  spaghetti bolognese  lazania  \
users                                                                       
Ula                 4.0                 5.0                  0.0      0.0   
Monika              0.0                 0.0                  0.0      0.0   
Maciek              2.0                 0.0                  5.0      5.0   
Kasper              1.0                 0.0                  1.0      0.0   
Filip               0.0                 0.0                  5.0      5.0   
Ola                 0.0                 3.0                  0.0      2.0   
Patrycja            0.0                 0.0                  0.0      4.0   
Juliusz             0.0                 0.0                  0.0      5.0   
Matusz              0.0                 0.0                  4.0      5.0   
Konrad              0.0                 0.0                  0.0      0.0   
Rafał               0.0                 0.0                  2.0      0.0   
Andrzej             0.0                 0.0                  0.0      5.0   
Mateusz Daniel      0.0                 0.0                  0.0      0.0   

                pierogi  czebureki  babka ziemniaczana  kaszanka  kutia  \
users                                                                     
Ula                 0.0        0.0                 0.0       0.0    0.0   
Monika              5.0        0.0                 5.0       3.0    0.0   
Maciek              0.0        4.0                 1.0       1.0    0.0   
Kasper              2.0        0.0                 1.0       0.0    5.0   
Filip               4.0        0.0                 4.0       3.0    0.0   
Ola                 5.0        0.0                 4.0       1.0    2.0   
Patrycja            4.0        0.0                 0.0       1.0    0.0   
Juliusz             5.0        0.0                 5.0       0.0    0.0   
Matusz              5.0        0.0                 5.0       4.0    0.0   
Konrad              5.0        0.0                 5.0       0.0    0.0   
Rafał               0.0        0.0                 2.0       0.0    0.0   
Andrzej             5.0        0.0                 3.0       0.0    5.0   
Mateusz Daniel      0.0        0.0                 0.0       0.0    0.0   

                Pizza Neapolitanska  ...  Schabowy  \
users                                ...             
Ula                             0.0  ...       0.0   
Monika                          4.0  ...       0.0   
Maciek                          5.0  ...       0.0   
Kasper                          1.0  ...       5.0   
Filip                           1.0  ...       5.0   
Ola                             0.0  ...       3.0   
Patrycja                        5.0  ...       4.0   
Juliusz                         5.0  ...       5.0   
Matusz                          0.0  ...       5.0   
Konrad                          5.0  ...       0.0   
Rafał                           4.0  ...       5.0   
Andrzej                         0.0  ...       5.0   
Mateusz Daniel                  0.0  ...       5.0   

                gnocchi z chorizo i szpinakiem  Grzanka z serem  \
users                                                             
Ula                                        0.0              0.0   
Monika                                     0.0              0.0   
Maciek                                     0.0              0.0   
Kasper                                     0.0              0.0   
Filip                                      0.0              0.0   
Ola                                        0.0              0.0   
Patrycja                                   0.0              3.0   
Juliusz                                    0.0              0.0   
Matusz                                     0.0              4.0   
Konrad                                     0.0              0.0   
Rafał                                      4.0              0.0   
Andrzej                                    0.0      

##### Funkcja zwracająca użytkowników z danej grupy (clustera) bez podanego jako parametr użytkownika

In [116]:
def get_users_from_group(group, user_name):
    
    # Wypisanie wszystkich stworzonych grup
    users_group = df['Group']

    # Stworzenie tablicy wypełnionej numerem grupy podanej jako parametr o wielkości takiej jak liczba użytkowników
    group_array = np.repeat(group, 13)

    # Znalezienie indeksów tych użytkowników, których grupa jest równa wybranej grupie podanej jako parametr
    group_indices = np.where(users_group == group_array)[0]
    
    # Dane bez kolumny z grupami
    df_without_groups = df.drop(columns=['Group'])

    # Zamiana indeksów na imiona użytkowników
    users = df_without_groups.iloc[group_indices].index.tolist()

    # Usunięcie podanego jako parametr użytkownika
    users.remove(user_name)
    
    return users

##### Funkcja zwracająca listę rekomendowanych produktów, przyjmująca jako argument użytkowników spośród których tworzy tą listę 

In [121]:
def get_product_from_other_users(others):
  
  # Stworzenie pustej listy rekomendowanych produktów
  recommended_products = set()

  # Dla każdego użytkownika z listy
  for user in others:

    # Pobranie oceny użytkownika
    user_ratings = df.loc[user]

    # Jeśli ocena produktu = 5, to dodaję go do listy rekomendowanych produktów
    for product, rating in user_ratings.items():
      if rating == 5:
        recommended_products.add(product)
    
    return recommended_products

##### Funkcja przewidująca na podstawie danych użytkownika, do której grupy będzie należał

In [101]:
def predict_user_group(user_name):
  # Dane bez kolumny z grupami
  df_without_groups = df.drop(columns=['Group'])

  # Wczytwanie danych konkretnego użytkownika
  user_data = df_without_groups.loc[user_name, :]

  # Przerworzenie danych użytkownika do tablicy aby móc zastosować przewidywanie grupy
  user_data_array = np.array(user_data.values).reshape(1, -1)

  # Przypisanie użytkownika do jednej z grup
  predicted_group = kmeans.predict(user_data_array)
  return predicted_group

##### Przewidzenie grupy, do której należą członkowie naszej grupy na zajęciach (poza Asią, której nie było na zajęciach gdy uzupełnialiśmy formularz z preferencjami)

In [104]:
Monika_predicted_group = predict_user_group('Monika')
Monika_predicted_group

array([2])

In [105]:
Patrycja_predicted_group = predict_user_group('Patrycja')
Patrycja_predicted_group

array([1])

In [106]:
Ola_predicted_group = predict_user_group('Ola')
Ola_predicted_group

array([2])

#### Znalezienie użytkowników, którzy należą do tych samych grup

In [119]:
users_from_Monika_group = get_users_from_group(Monika_predicted_group, 'Monika')
users_from_Monika_group

['Ola', 'Matusz']

In [118]:
users_from_Patrycja_group = get_users_from_group(Patrycja_predicted_group, 'Patrycja')
users_from_Patrycja_group

['Filip', 'Juliusz', 'Konrad', 'Andrzej']

In [120]:
users_from_Ola_group = get_users_from_group(Ola_predicted_group, 'Ola')
users_from_Ola_group

['Monika', 'Matusz']

#### Znalezienie sugerowanych produktów, dla każdego z użytkowników

In [122]:
Monika_recommendations = get_product_from_other_users(users_from_Monika_group)
Monika_recommendations

{'Barszcz czerwony', 'pierogi'}

In [123]:
Patrycja_recommendations = get_product_from_other_users(users_from_Patrycja_group)
Patrycja_recommendations

{'Kebab',
 'Schabowy',
 'Spaghetti Neapolitana',
 'lazania',
 'spaghetti bolognese'}

In [124]:
Ola_recommendations = get_product_from_other_users(users_from_Ola_group)
Ola_recommendations

{'Barszcz czerwony', 'babka ziemniaczana', 'pierogi'}